---
title: "xts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## xts

```{r}
library(xts)

class(UKgas)

ukgas <- as.xts(UKgas)

## Pobieranie danych:
ukgas["1985"] # wybrany rok
ukgas["1984/1985"] # zakres dat
ukgas["1984/"] # po dacie
ukgas["/1961"] # do daty

gas <- ukgas["1984/1985"]

rollapply(gas, width = 3, align = "center", sum)
rollapply(gas, width = 3, align = "left", sum)
rollapply(gas, width = 3, align = "right", sum)
```

### xta apply

```{r}
ukgas <- as.xts(UKgas)
apply.yearly(ukgas, sum)
apply.yearly(ukgas, mean)
```

```{r}
library(quantmod)

data <- getSymbols("^GSPC", auto.assign = FALSE)

class(data) # getSymbols od razu pobiera xts

# Wybranie kolumn OHLC i zmiana nazw kolumn
data <- data[,c(1,2,3,4)] 
colnames(data) <- c("Open", "High", "Low", "Close")

# Konwersja danych dziennych na miesieczne:
```

```{r}
# Przygotowanie funkcji dla apply.monthly
x <- data
x[1,1]
max(x)
min(x)
x[nrow(x), ncol(x)]

# Nie działa!
# c(
#   x[1,1],
#   max(x),
#   min(x),
#   x[nrow(x), ncol(x)])

x <- as.matrix(x)
c(
  Open = x[1,1],
  High = max(x),
  Low  = min(x),
  Close = x[nrow(x), ncol(x)])


singleOHLC <- function(x) {
  x <- as.matrix(x)
  c(
    Open = x[1,1],
    High = max(x),
    Low  = min(x),
    Close = x[nrow(x), ncol(x)])
}

singleOHLC(data)

```

```{r}
## Ostatecznie:

monthly <- apply.monthly(data, singleOHLC)

data.monthly <- apply.monthly(data, function(x) {
  x <- as.matrix(x)
  c(Open = x[1,1], High = max(x), Low = min(x), Close = x[nrow(x), ncol(x)])
})

plot(data[, "Close"], main = "SP500 daily vs monthly")
lines(data.monthly[, "Close"], col = "red", lwd = 2)
```
